### ISSUE TITLE
Is not workung for me

### ISSUE THREAD

**Issue by rctvhd** [rokudev/podcast-player-channel#1]
Hello! I downloaded this xample, thanks for that.
But when run the channel on eclipse, I only got the flash screen.

Any help?

Thanks

Edward R

**Comment by LockChristian** [comment]
Hi Edward,

I noticed that you posted on the developer blog with your issues. I wanted to let you know that we responded to your issue there but if you are still having trouble loading the channel please let me know and I can help you troubleshoot any issues that you have.
