### ISSUE TITLE
Loading feed backwards

### ISSUE THREAD

**Issue by nickcraig** [rokudev/podcast-player-channel#2]
When loading in my feed(http://infectionpodcast.com/feed/podcast/) the app loads episode 1 instead of the latest episode first.

**Comment by dannykng** [comment]
Added a [feature to reverse the sorting order](https://github.com/rokudev/podcast-player-channel/commit/ff76cbea620182620a5572b851fe0304cbc9ae71). Check it out and let us know if there are any issues.
